# the networks should be created before the services
# enter the command `docker network create NETWORKNAME` to create the network, same for the other networks

services:
    proxy:
        # you don't need proxy if you don't have one or more web services
        container_name: proxy
        image: nginx:latest
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        networks:
            - nginx-proxy

    discordbot:
        container_name: notipy-discordbot
        image: notipy
        restart: unless-stopped
        volumes:
            - ./discordbot:/app
        working_dir: /app
        env_file:
            - var.env
        environment:
            - DISCORD_TOKEN=${DISCORD_TOKEN}
            - DEBUG=1 # set to 1 to enable debug mode
        expose:
            - ${DISCORD_PORT}
        command:
            - python
            - main.py
        networks:
            - nginx-proxy

    backend:
        container_name: notipy-backend
        image: notipy
        restart: unless-stopped
        env_file:
            - var.env
        expose:
            - ${MY_BACKEND_PORT}
        volumes:
            - ./backend:/app
        working_dir: /app
        command:
            - python
            - main.py
        networks:
            - nginx-proxy
            - notipy_backend

    database:
        container_name: notipy-database # change this -> change backend var.py
        image: mysql:latest
        restart: unless-stopped
        env_file:
            - var.env
        expose:
            - ${MYSQL_TCP_PORT}
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        volumes:
            - ./database:/var/lib/mysql
        networks:
            - notipy_backend
        command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
        # this is to make sure the database is utf8mb4, you can use without this, but some letters can break


networks:
    nginx-proxy:
        external: true
    notipy_backend:
        external: true